package com.webHook.Correo;

public class Html {
	 private String htmlAprobado;

	public String htmlRechazado;
	
	private String htmlDomiciliado;
		
	public String getHtmlRechazado() {
		return htmlRechazado;
	}

	public void setHtmlRechazado(String titular,String codigoError, String oid) {
		this.htmlRechazado = "<html>\r\n"
				+ "    <head>\r\n"
				+ "        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n"
				+ "        <title>Pago en linea</title>\r\n"
				+ "        <style type=\"text/css\">\r\n"
				+ "            /* Reset -------------------------------------------------------------------- */\r\n"
				+ "\r\n"
				+ "            /* OPPS --------------------------------------------------------------------- */\r\n"
				+ "\r\n"
				+ "            h3 {\r\n"
				+ "                margin-bottom: 10px;\r\n"
				+ "                font-size: 15px;\r\n"
				+ "                font-weight: 600;\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "            .opps {\r\n"
				+ "                width: 550px; \r\n"
				+ "                border-radius: 4px;\r\n"
				+ "                box-sizing: border-box;\r\n"
				+ "                padding: 0 45px;\r\n"
				+ "                margin: 40px auto;\r\n"
				+ "                overflow: hidden;\r\n"
				+ "                border: 1px solid #b0afb5;\r\n"
				+ "                font-family: 'Open Sans', sans-serif;\r\n"
				+ "                color: #4f5365;\r\n"
				+ "					background-color: white;"
				+ "            }\r\n"
				+ "\r\n"
				+ "            .opps-reminder {\r\n"
				+ "                position: relative;\r\n"
				+ "                top: -1px;\r\n"
				+ "                padding: 9px 0 10px;\r\n"
				+ "                font-size: 11px;\r\n"
				+ "                text-transform: uppercase;\r\n"
				+ "                text-align: center;\r\n"
				+ "                color: #ffffff;\r\n"
				+ "                background: #000000;\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "            .opps-brand {\r\n"
				+ "                position: relative;\r\n"
				+ "                top: -1px;\r\n"
				+ "                padding: 9px 0 10px;\r\n"
				+ "                font-size: 40px;\r\n"
				+ "                text-transform: uppercase;\r\n"
				+ "                text-align: center;\r\n"
				+ "                color: #000000;\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "            .opps-info {\r\n"
				+ "                margin-top: 26px;\r\n"
				+ "                position: relative;\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "            .opps-reference {\r\n"
				+ "                margin-top: 14px;\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "            h1 {\r\n"
				+ "                font-size: 27px;\r\n"
				+ "                color: #000000;\r\n"
				+ "                text-align: center;\r\n"
				+ "                margin-top: -1px;\r\n"
				+ "                padding: 6px 0 7px;\r\n"
				+ "                border: 1px solid #b0afb5;\r\n"
				+ "                border-radius: 4px;\r\n"
				+ "                background: #f8f9fa;\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "        </style>\r\n"
				+ "        <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:400,600,700\" rel=\"stylesheet\">\r\n"
				+ "    </head>\r\n"
				+ "    <body>\r\n"
				+ "              <div class=\"opps\">\r\n"
				+ "                  <div class=\"opps-header\">\r\n"
				+ "                      <div class=\"opps-reminder\">Notificación de Pago en Linea</div>\r\n"
				+ "                      <div class=\"opps-info\">\r\n"
				+ "                          <div class=\"opps-brand\">Pago No Aprobado</div>\r\n"
				+ "                      </div>\r\n"
				+ "                      <div class=\"opps-reference\">\r\n"
				+ "                          <h3> Hola "+titular+" </h3>\r\n"
				+ "                          <h3> Gracias por realizar tu pago a través de nuestros medios digitales. </h3>\r\n"
				+ "                          <h3>Lamentamos informarte que tu pago no pudo ser procesado por nuestro sistema, por favor intenta nuevamente más tarde</h3>\r\n"
				+ "                          \r\n"
				+ "      					<h1>Código de Error: "+codigoError+"</h1>\r\n"
				+ "      					<h1>Order Id:  "+oid+"</h1>\r\n"
				+ "                          <h3 style=\"font-style: oblique; margin-bottom: 50px;\">¡Impulsando tu mejor versión a través del deporte!</h3>\r\n"
				+ "                      </div>\r\n"
				+ "                  </div>\r\n"
				+ "              </div>\r\n"
				+ "          </body>\r\n"
				+ "</html>";
	}


	public String getHtmlAprobado() {
		return htmlAprobado;
	}

	public void setHtmlAprobado(String nombre,int idCliente, String noMembresia,String fechaPago,String horaPago,String importe,String noAutorizacion,String oid) {
		this.htmlAprobado = "<html>\r\n"
				+ "    <head>\r\n"
				+ "        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n"
				+ "        <title>Pago en linea</title>\r\n"
				+ "        <style type=\"text/css\">\r\n"
				+ "            /* Reset -------------------------------------------------------------------- */\r\n"
				+ "\r\n"
				+ "            /* OPPS --------------------------------------------------------------------- */\r\n"
				+ "\r\n"
				+ "            h3 {\r\n"
				+ "                margin-bottom: 10px;\r\n"
				+ "                font-size: 15px;\r\n"
				+ "                font-weight: 600;\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "            .opps {\r\n"
				+ "                width: 550px; \r\n"
				+ "                border-radius: 4px;\r\n"
				+ "                box-sizing: border-box;\r\n"
				+ "                padding: 0 45px;\r\n"
				+ "                margin: 40px auto;\r\n"
				+ "                overflow: hidden;\r\n"
				+ "                border: 1px solid #b0afb5;\r\n"
				+ "                font-family: 'Open Sans', sans-serif;\r\n"
				+ "                color: #4f5365;\r\n"
				+ "					background-color: white;"
				+ "            }\r\n"
				+ "\r\n"
				+ "            .opps-reminder {\r\n"
				+ "                position: relative;\r\n"
				+ "                top: -1px;\r\n"
				+ "                padding: 9px 0 10px;\r\n"
				+ "                font-size: 11px;\r\n"
				+ "                text-transform: uppercase;\r\n"
				+ "                text-align: center;\r\n"
				+ "                color: #ffffff;\r\n"
				+ "                background: #000000;\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "            .opps-brand {\r\n"
				+ "                position: relative;\r\n"
				+ "                top: -1px;\r\n"
				+ "                padding: 9px 0 10px;\r\n"
				+ "                font-size: 40px;\r\n"
				+ "                text-transform: uppercase;\r\n"
				+ "                text-align: center;\r\n"
				+ "                color: #000000;\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "            .opps-info {\r\n"
				+ "                margin-top: 26px;\r\n"
				+ "                position: relative;\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "            .opps-reference {\r\n"
				+ "                margin-top: 14px;\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "            h1 {\r\n"
				+ "                font-size: 27px;\r\n"
				+ "                color: #000000;\r\n"
				+ "                text-align: center;\r\n"
				+ "                margin-top: -1px;\r\n"
				+ "                padding: 6px 0 7px;\r\n"
				+ "                border: 1px solid #b0afb5;\r\n"
				+ "                border-radius: 4px;\r\n"
				+ "                background: #f8f9fa;\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "        </style>\r\n"
				+ "        <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:400,600,700\" rel=\"stylesheet\">\r\n"
				+ "    </head>\r\n"
				+ "    <body>\r\n"
				+ "              <div class=\"opps\">\r\n"
				+ "                  <div class=\"opps-header\">\r\n"
				+ "                      <div class=\"opps-reminder\">Notificación de Pago en Linea</div>\r\n"
				+ "                      <div class=\"opps-info\">\r\n"
				+ "                          <div class=\"opps-brand\">Pago Aprobado</div>\r\n"
				+ "                      </div>\r\n"
				+ "                      <div class=\"opps-reference\">\r\n"
				+ "                          <h2> GRACIAS POR TU PAGO </h2>\r\n"
				+ "                          <h3> Tu pago se registró de manera exitosa </h3>\r\n"
				+ "                          <h3> Hola "+nombre+" </h3>\r\n"
				+ "                          <h3> Gracias por realizar tu pago a través de nuestros medios digitales. </h3>\r\n"
				+ "                          <h3>Aqui tienes los datos de tu pago:</h3>\r\n"
				+ "      					<h1>ID de usuario: "+idCliente+"</h1>\r\n"
				+ "      					<h1>Número de membresía: "+noMembresia+"</h1>\r\n"
				+ "      					<h1>Fecha: "+fechaPago+"</h1>\r\n"
				+ "      					<h1>Hora: "+horaPago+"</h1>\r\n"
				+ "      					<h1>Importe pagado: "+importe+"</h1>\r\n"
				+ "      					<h1>No. Autorización: "+noAutorizacion+"</h1>\r\n"
				+ "      					<h1>Order Id:  "+oid+"</h1>\r\n"
				+ "                          <h3> Para tu comodidad te invitamos a domiciliar tu pago, solicita informacion en atención a clientes de tu club </h3>\r\n"
				+ "                          <h3 style=\"font-style: oblique; margin-bottom: 50px;\">¡Impulsando tu mejor versión a través del deporte!</h3>\r\n"
				+ "                      </div>\r\n"
				+ "                  </div>\r\n"
				+ "              </div>\r\n"
				+ "          </body>\r\n"
				+ "</html>";
	}

	public String getHtmlDomiciliado() {
		return htmlDomiciliado;
	}

	public void setHtmlDomiciliado(String nombre,int idCliente, String noMembresia,String fechaPago,String horaPago,String importe,String noAutorizacion,String oid) {
		this.htmlDomiciliado = "<html>\r\n"
				+ "    <head>\r\n"
				+ "        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n"
				+ "        <title>Pago en linea</title>\r\n"
				+ "        <style type=\"text/css\">\r\n"
				+ "            /* Reset -------------------------------------------------------------------- */\r\n"
				+ "\r\n"
				+ "            /* OPPS --------------------------------------------------------------------- */\r\n"
				+ "\r\n"
				+ "            h3 {\r\n"
				+ "                margin-bottom: 10px;\r\n"
				+ "                font-size: 15px;\r\n"
				+ "                font-weight: 600;\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "            .opps {\r\n"
				+ "                width: 550px; \r\n"
				+ "                border-radius: 4px;\r\n"
				+ "                box-sizing: border-box;\r\n"
				+ "                padding: 0 45px;\r\n"
				+ "                margin: 40px auto;\r\n"
				+ "                overflow: hidden;\r\n"
				+ "                border: 1px solid #b0afb5;\r\n"
				+ "                font-family: 'Open Sans', sans-serif;\r\n"
				+ "                color: #4f5365;\r\n"
				+ "					background-color: white;"
				+ "            }\r\n"
				+ "\r\n"
				+ "            .opps-reminder {\r\n"
				+ "                position: relative;\r\n"
				+ "                top: -1px;\r\n"
				+ "                padding: 9px 0 10px;\r\n"
				+ "                font-size: 11px;\r\n"
				+ "                text-transform: uppercase;\r\n"
				+ "                text-align: center;\r\n"
				+ "                color: #ffffff;\r\n"
				+ "                background: #000000;\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "            .opps-brand {\r\n"
				+ "                position: relative;\r\n"
				+ "                top: -1px;\r\n"
				+ "                padding: 9px 0 10px;\r\n"
				+ "                font-size: 40px;\r\n"
				+ "                text-transform: uppercase;\r\n"
				+ "                text-align: center;\r\n"
				+ "                color: #000000;\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "            .opps-info {\r\n"
				+ "                margin-top: 26px;\r\n"
				+ "                position: relative;\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "            .opps-reference {\r\n"
				+ "                margin-top: 14px;\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "            h1 {\r\n"
				+ "                font-size: 27px;\r\n"
				+ "                color: #000000;\r\n"
				+ "                text-align: center;\r\n"
				+ "                margin-top: -1px;\r\n"
				+ "                padding: 6px 0 7px;\r\n"
				+ "                border: 1px solid #b0afb5;\r\n"
				+ "                border-radius: 4px;\r\n"
				+ "                background: #f8f9fa;\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "        </style>\r\n"
				+ "        <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:400,600,700\" rel=\"stylesheet\">\r\n"
				+ "    </head>\r\n"
				+ "    <body>\r\n"
				+ "              <div class=\"opps\">\r\n"
				+ "                  <div class=\"opps-header\">\r\n"
				+ "                      <div class=\"opps-reminder\">Notificación de Pago en Linea</div>\r\n"
				+ "                      <div class=\"opps-info\">\r\n"
				+ "                          <div class=\"opps-brand\">Pago Aprobado</div>\r\n"
				+ "                          <div class=\"opps-brand\">¡Felicidades, ya estás domiciliado!</div>\r\n"
				+ "                      </div>\r\n"
				+ "                      <div class=\"opps-reference\">\r\n"
				+ "                          <h2> GRACIAS POR TU PAGO </h2>\r\n"
				+ "                          <h3> Tu pago se registró de manera exitosa </h3>\r\n"
				+ "                          <h3> Hola "+nombre+" </h3>\r\n"
				+ "                          <h3> Gracias por realizar tu pago a través de nuestros medios digitales. </h3>\r\n"
				+ "                          <h3>Aqui tienes los datos de tu pago:</h3>\r\n"
				+ "      					<h1>ID de usuario: "+idCliente+"</h1>\r\n"
				+ "      					<h1>Número de membresía: "+noMembresia+"</h1>\r\n"
				+ "      					<h1>Fecha: "+fechaPago+"</h1>\r\n"
				+ "      					<h1>Hora: "+horaPago+"</h1>\r\n"
				+ "      					<h1>Importe pagado: "+importe+"</h1>\r\n"
				+ "      					<h1>No. Autorización: "+noAutorizacion+"</h1>\r\n"
				+ "      					<h1>Order Id:  "+oid+"</h1>\r\n"
				+ "                          <h3 style=\"font-style: oblique; margin-bottom: 50px;\">¡Impulsando tu mejor versión a través del deporte!</h3>\r\n"
				+ "                      </div>\r\n"
				+ "                  </div>\r\n"
				+ "              </div>\r\n"
				+ "          </body>\r\n"
				+ "</html>";
	}
	 
	 
}
